name: Validate Registry

on:
  pull_request:
    paths:
      - registry.json
  push:
    paths:
      - registry.json

jobs:
  validate:
    uses: DockyardMods/tooling/.github/workflows/validate-registry.yml@main
    with:
      registry_path: ./registry.json
      registry_schema_url: https://raw.githubusercontent.com/DockyardMods/the-dockyard/main/schemas/registry.schema.json
      schema_base_url: https://raw.githubusercontent.com/DockyardMods/the-dockyard/main/schemas
