name: Validate Registry

on:
  pull_request:
    paths:
      - registry.json
  push:
    paths:
      - registry.json
  workflow_dispatch:

jobs:
  validate:
    uses: DockyardMods/dockyardmods/.github/workflows/validate-registry.yml@main
    with:
      registry_path: ./registry.json
